<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestEveryIBE</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e8b74193-d2ec-4019-b915-a5bb3d63f038</testSuiteGuid>
   <testCaseLink>
      <guid>c4ffeb9b-5324-4776-96cc-f0285d260e0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/audi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b0a3b75-80c2-4b67-97fe-53b9a0e92158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>271e30e0-854c-4c98-8bee-c3f0a2915a20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>deed73aa-f4eb-4658-bdd0-ce86015f3db1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/baldaja</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eda68c86-0317-46b2-a555-40884ecdb501</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1af8665e-6d1f-4e5d-ab43-25f494f5c9a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58c261d8-150b-4ed1-b67b-aa25f7f24ceb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/barmer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ad2a8cc-a95b-4ff7-a011-0c3bc619a162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b399c940-e1ab-4a37-a307-3089f78e3b18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d7b58fa-f6d4-4447-8145-ec01ac297626</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/bearingpoint</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4de7fcf9-1f7d-48a5-bb1c-8c26b878783c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0359596a-7888-4907-843e-9357d50ce3c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f15b407-7bb4-4e0d-ab15-e9e1328473e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/commerzbank</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dfa7ffa-6374-48f8-8691-22c13aa494d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbef574-b0d6-4dfc-86e8-ba3d8dc9770d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c2bf96a-eb4c-4306-826c-fd9e6a992b31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/covestro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07b31d39-8523-4eac-8945-6c506e97daf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43d5e89c-0fa7-416f-919f-2b076e37ed56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b514f824-7a7d-4883-bd29-46bffbd8ccd3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/freshfields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21327bf9-63e0-4c97-b90b-c532b63cd6df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8128728-d64e-4ab5-a6a7-88b76995c270</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>128a21bd-02de-4a9f-bb3d-18d6876c4876</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/goomo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>209676ee-7d24-48b1-b473-739f5a2dcc27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0838c624-75f5-4479-bfe2-e026d538f4bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>288a8044-c89d-454f-b901-68a74c084d28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/microfuzzy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e81c3bf-c389-4083-a015-c5f7f7d3a93a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56974495-c829-49fb-8f0b-d06d99289c76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97359bb1-9451-46a3-bdd0-c2b951f504a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/roche</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77b0973-3dcf-4187-ace2-49032c6c5f9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e65de4bf-4c55-47ee-a3b6-e336a80cc973</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc24c55a-8b55-4758-a676-08c6a94ee34e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/roomit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5477a3a5-1e91-480e-bbe7-87c3409439fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>357b8695-6e78-4d81-a11d-9736ec485879</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d717bd2-192d-486e-bdb7-59039a7cac7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tmdfriction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd79e2c4-41c6-4ab6-95fd-5eb6a7877e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf87f1c0-dca8-428c-aa3c-7f92accce4b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf2914cc-d511-4190-999f-80535fa3796c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/zeb</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec21e4b-4d98-40aa-9329-d448e40bfb91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b68a498-7752-4125-9960-4170bf151fce</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
